name: eval-sampling-methods

channels:
- conda-forge
- anaconda

dependencies:
- python==3.9.10
- nb_conda_kernels
- pip
- ipython
- imbalanced-learn
- tqdm
- numpy
- scipy
- pandas
- matplotlib
- seaborn
- colorama
- optuna
- scikit-learn==1.2.2
- sweetviz
- xgboost
- scikit-optimize
- ipython
- ipywidgets
- matplotlib==3.6.0
- seaborn==0.12.0
- ipywidgets==8.0.2


- pip:
  # Machine Learning
  - psutil
  - tabulate
